name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          git config --global --add safe.directory /var/www/dylanbay.dev
          cd /var/www/dylanbay.dev
          git pull origin main
          chown -R www-data:www-data /var/www/dylanbay.dev
          systemctl reload nginx
